### ISSUE TITLE
Review use cases for useMemo

### ISSUE THREAD

**Issue by albertvazquezm** [mallorcabootcamp/codos-app-client#46]
We were using useMemo to query the API in the past. This should be avoided.

Please, check this document and update our codebase as necessary. API calls should always use useEffect.

https://dev.to/devcord/react-hooks-useeffect-usecallback-usememo-3o42

**Comment by Ralvgar** [comment]
Checked! If I don't understand badly I only have to read that document, I think we have everything fine in our code atm.
